---
- name: Deploy Grafana
  hosts: monitoring
  become: true

  tasks:
    - name: Create Grafana data directory
      ansible.builtin.file:
        path: /opt/grafana
        state: directory
        owner: "472"
        group: "472"
        mode: '0755'

    - name: Run Grafana container
      community.docker.docker_container:
        name: grafana
        image: grafana/grafana:latest
        state: started
        restart_policy: always
        published_ports:
          - "3000:3000"
        volumes:
          - /opt/grafana:/var/lib/grafana
        env:
          GF_SECURITY_ADMIN_USER: admin
          GF_SECURITY_ADMIN_PASSWORD: "{{ vault_grafana_admin_password }}"
