---
- name: Deploy Node Exporter
  hosts: all
  become: true

  tasks:
    - name: Run Node Exporter
      community.docker.docker_container:
        name: node-exporter
        image: prom/node-exporter:latest
        state: started
        restart_policy: always
        network_mode: host
        pid_mode: host
        volumes:
          - /:/host:ro,rslave
        command:
          - --path.rootfs=/host
